### ISSUE TITLE
Traceback (most recent call last) after running ae_train exp_group/my_autoencoder

### ISSUE THREAD

**Issue by AminSeffo** [DLR-RM/AugmentedAutoencoder#110]
Hey everyone,

first of all I would like to thank you for this helpful pipeline.
I followed all installation instructions but I get always this error when I run ```ae_train exp_group/my_autoencoder``` to start the training.

**System Info**

 * Ubuntu: 20.04
 * Virtual enviroment
 * Python version: 3.8.10
 * tensorflow-gpu = 2.6.0
 * numpy = 1.22.0

```
/home/vrt/augmented_autoencoder_env/lib/python3.8/site-packages/keras/legacy_tf_layers/convolutional.py:536: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  warnings.warn('`tf.layers.conv2d` is deprecated and '
/home/vrt/augmented_autoencoder_env/lib/python3.8/site-packages/keras/engine/base_layer_v1.py:1676: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
/home/vrt/augmented_autoencoder_env/lib/python3.8/site-packages/keras/legacy_tf_layers/core.py:513: UserWarning: `tf.layers.flatten` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Flatten` instead.
  warnings.warn('`tf.layers.flatten` is deprecated and '
/home/vrt/augmented_autoencoder_env/lib/python3.8/site-packages/keras/legacy_tf_layers/core.py:236: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  warnings.warn('`tf.layers.dense` is deprecated and '
128 128 3
[[8, 8], [16, 16], [32, 32], [64, 64]]
(None, 128, 128, 3)
(None, 128, 128, 3)
using egl   0% |                                                                           | 0 / 20000 ETA:  --:--:-- 
Unable to load numpy_formathandler accelerator from OpenGL_accelerate
Traceback (most recent call last):
  File "/home/vrt/augmented_autoencoder_env/bin/ae_train", line 8, in <module>
    sys.exit(main())
  File "/home/vrt/augmented_autoencoder_env/lib/python3.8/site-packages/auto_pose/ae/ae_train.py", line 91, in main
    dataset.get_training_images(dataset_path, args)
  File "/home/vrt/augmented_autoencoder_env/lib/python3.8/site-packages/auto_pose/ae/dataset.py", line 92, in get_training_images
    self.render_training_images()
  File "/home/vrt/augmented_autoencoder_env/lib/python3.8/site-packages/auto_pose/ae/dataset.py", line 244, in render_training_images
    bgr_x, depth_x = self.renderer.render(
  File "/home/vrt/augmented_autoencoder_env/lib/python3.8/site-packages/auto_pose/ae/utils.py", line 15, in decorator
    setattr(self, attribute, function(self))
  File "/home/vrt/augmented_autoencoder_env/lib/python3.8/site-packages/auto_pose/ae/dataset.py", line 71, in renderer
    renderer = meshrenderer_phong.Renderer(
  File "/home/vrt/augmented_autoencoder_env/lib/python3.8/site-packages/auto_pose/meshrenderer/meshrenderer_phong.py", line 22, in __init__
    self._fbo = gu.Framebuffer( { GL_COLOR_ATTACHMENT0: gu.Texture(GL_TEXTURE_2D, 1, GL_RGB8, W, H),
  File "/home/vrt/augmented_autoencoder_env/lib/python3.8/site-packages/auto_pose/meshrenderer/gl_utils/fbo.py", line 19, in __init__
    glNamedFramebufferTexture(self.__id, k, attachement.id, 0)
  File "/home/vrt/augmented_autoencoder_env/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
```

**Comment by AminSeffo** [comment]
Update:
I checked my installed pip packages and saw that I have tensorflow-gpu: 2.9.1 and not **2.6.0**

**Comment by MartinSmeyer** [comment]
Hey @AminSeffo ,

> I checked my installed pip packages and saw that I have tensorflow-gpu: 2.9.1 and not 2.6.0

That might be a problem.

Otherwise, it seems it is crashing at the rendering. So I assume that your 3D Model is in the wrong format. It needs to be a `.ply` file with vertex colors.

**Comment by AminSeffo** [comment]
Hey @MartinSmeyer ,

thank your very much for your response.
I have realized that my `.ply` file was not exported in ASCII. I finally got the pipeline to work by creating a conda environment from the `YAML` file.
best regards
