### ISSUE TITLE
[question] Unable to train custom .ply file.

### ISSUE THREAD

**Issue by hirohitokato** [DLR-RM/AugmentedAutoencoder#119]
**Describe the bug**
When I tried to train the model, the following error occurred and failed to do it. Is it possible for your environment to train it?

```sh
ser@user-VirtualBox:~$ ae_train exp_group/my_autoencoder -d
2022-09-14 10:07:09.900508: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-14 10:07:10.105534: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-09-14 10:07:10.903166: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/user/.local/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.6/lib64::/usr/local/cuda/lib64:/usr/local/lib
2022-09-14 10:07:10.903352: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/user/.local/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.6/lib64::/usr/local/cuda/lib64:/usr/local/lib
2022-09-14 10:07:10.903409: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/encoder.py:43: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  x = tf.layers.conv2d(
/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/encoder.py:54: UserWarning: `tf.layers.flatten` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Flatten` instead.
  encoder_out = tf.layers.flatten(x)
/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/encoder.py:62: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  z = tf.layers.dense(
128 128 3
[[8, 8], [16, 16], [32, 32], [64, 64]]
/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/decoder.py:44: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  x = tf.layers.dense(
/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/decoder.py:56: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  x = tf.layers.conv2d(
/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/decoder.py:77: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  x = tf.layers.conv2d(
(None, 128, 128, 3)
(None, 128, 128, 3)
/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/decoder.py:93: UserWarning: `tf.layers.flatten` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Flatten` instead.
  x_flat = tf.layers.flatten(self.x)
/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/decoder.py:94: UserWarning: `tf.layers.flatten` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Flatten` instead.
  reconstruction_target_flat = tf.layers.flatten(self._reconstruction_target)
using glfw  0% |                                                       | 0 / 20000 ETA:  --:--:-- 
Unable to load numpy_formathandler accelerator from OpenGL_accelerate
Traceback (most recent call last):
  File "/home/user/.local/bin/ae_train", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/ae_train.py", line 91, in main
    dataset.get_training_images(dataset_path, args)
  File "/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/dataset.py", line 92, in get_training_images
    self.render_training_images()
  File "/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/dataset.py", line 244, in render_training_images
    bgr_x, depth_x = self.renderer.render(
  File "/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/utils.py", line 15, in decorator
    setattr(self, attribute, function(self))
  File "/home/user/.local/lib/python3.8/site-packages/auto_pose/ae/dataset.py", line 71, in renderer
    renderer = meshrenderer_phong.Renderer(
  File "/home/user/.local/lib/python3.8/site-packages/auto_pose/meshrenderer/meshrenderer_phong.py", line 22, in __init__
    self._fbo = gu.Framebuffer( { GL_COLOR_ATTACHMENT0: gu.Texture(GL_TEXTURE_2D, 1, GL_RGB8, W, H),
  File "/home/user/.local/lib/python3.8/site-packages/auto_pose/meshrenderer/gl_utils/fbo.py", line 19, in __init__
    glNamedFramebufferTexture(self.__id, k, attachement.id, 0)
  File "/home/user/.local/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
```

**System Info**
Describe the characteristic of your environment:
 * GPU models and configuration : NVIDIA GeForce GTX 1650 Ti
 * Python version : 3.9.12
 * OpenGL version
 * Windows 10, Ubuntu 20.04 runs on WSL2

**Additional context**

**Comment by MartinSmeyer** [comment]
Hey @hirohitokato,

 Sorry for the late answer, which 3D model are you using for training?

**Comment by MartinSmeyer** [comment]
Please make sure it is in PLY format and has vertex colors assigned.
