### ISSUE TITLE
NameError: global name 'glCreateTextures' is not defined

### ISSUE THREAD

**Issue by SonOfCoding** [DLR-RM/AugmentedAutoencoder#2]
Hi, I followed the instruction and I got this problem. I did pip install pyopengl ((py2.7_edc) edison@amax-server:~/edison/aae/AugmentedAutoencoder/AE_WORKSPACE_PATH$ pip install pyopengl
Requirement already satisfied: pyopengl in /home/edison/py2.7_edc/lib/python2.7/site-packages (3.1.0)
)

This is the problem, Can you please help me? Thank you.

(py2.7_edc) edison@amax-server:~/edison/aae/AugmentedAutoencoder/AE_WORKSPACE_PATH$ ae_train exp_group/my_autoencoder -d
128 128 3
[[8, 8], [16, 16], [32, 32], [64, 64]]
(?, 128, 128, 3)
(?, 128, 128, 3)
Traceback (most recent call last):20000 ] |                                                                                                                                 | (ETA:  --:--:--)
  File "/home/edison/py2.7_edc/bin/ae_train", line 11, in <module>
    sys.exit(main())
  File "/home/edison/py2.7_edc/local/lib/python2.7/site-packages/auto_pose/ae/ae_train.py", line 90, in main
    dataset.get_training_images(dataset_path, args)
  File "/home/edison/py2.7_edc/local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 93, in get_training_images
    self.render_training_images()
  File "/home/edison/py2.7_edc/local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 246, in render_training_images
    bgr_x, depth_x = self.renderer.render(
  File "/home/edison/py2.7_edc/local/lib/python2.7/site-packages/auto_pose/ae/utils.py", line 15, in decorator
    setattr(self, attribute, function(self))
  File "/home/edison/py2.7_edc/local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 75, in renderer
    float(self._kw['vertex_scale'])
  File "/home/edison/py2.7_edc/local/lib/python2.7/site-packages/auto_pose/meshrenderer/meshrenderer_phong.py", line 22, in __init__
    self._fbo = gu.Framebuffer( { GL_COLOR_ATTACHMENT0: gu.Texture(GL_TEXTURE_2D, 1, GL_RGB8, W, H),
  File "/home/edison/py2.7_edc/local/lib/python2.7/site-packages/auto_pose/meshrenderer/gl_utils/texture.py", line 11, in __init__
    glCreateTextures(tex_type, len(self.__id), self.__id)
NameError: global name 'glCreateTextures' is not defined

**Comment by MartinSmeyer** [comment]
same as:

https://github.com/DLR-RM/AugmentedAutoencoder/issues/1
