### ISSUE TITLE
how to use cad model to render

### ISSUE THREAD

**Issue by liujiayu1997** [DLR-RM/AugmentedAutoencoder#25]
I want to render my model with cad option ,however, i have used DWG, DXF,3DS and STL model type and have error as follow

(aae) gaobo@gaobo-ubuntu:~/SSD_ws$ ae_train exp_group/my_autoencoder -d
128 128 3
[[8, 8], [16, 16], [32, 32], [64, 64]]
(?, 128, 128, 3)
(?, 128, 128, 3)
Traceback (most recent call last):                                                                                                                                                                                |
  File "/home/gaobo/.local/bin/ae_train", line 10, in <module>
    sys.exit(main())
  File "/home/gaobo/.local/lib/python2.7/site-packages/auto_pose/ae/ae_train.py", line 90, in main
    dataset.get_training_images(dataset_path, args)
  File "/home/gaobo/.local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 93, in get_training_images
    self.render_training_images()
  File "/home/gaobo/.local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 245, in render_training_images
    bgr_x, depth_x = self.renderer.render( 
  File "/home/gaobo/.local/lib/python2.7/site-packages/auto_pose/ae/utils.py", line 15, in decorator
    setattr(self, attribute, function(self))
  File "/home/gaobo/.local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 68, in renderer
    float(self._kw['vertex_scale'])
  File "/home/gaobo/.local/lib/python2.7/site-packages/auto_pose/meshrenderer/meshrenderer.py", line 37, in __init__
    vert_norms = gu.geo.load_meshes(models_cad_files, vertex_tmp_store_folder, recalculate_normals=True)
  File "/home/gaobo/.local/lib/python2.7/site-packages/auto_pose/meshrenderer/gl_utils/geometry.py", line 54, in load_meshes
    scene = pyassimp.load(model_path, pyassimp.postprocess.aiProcess_Triangulate)
  File "/home/gaobo/anaconda3/envs/aae/lib/python2.7/site-packages/pyassimp/core.py", line 320, in load
    raise AssimpError('Could not import file!')
pyassimp.errors.AssimpError: Could not import file!

I just want to know which type of model can be used with cad option

**Comment by MartinSmeyer** [comment]
Hey!
You need a .ply file :)
