### ISSUE TITLE
ValueError: need more than 3 values to un pack

### ISSUE THREAD

**Issue by jinjuehui** [DLR-RM/AugmentedAutoencoder#7]
Hi, after I  create the training config file, and insert the paths of my 3d model, when I run "ae_train exp_group/my_autoencoder -d" I get following ValueError :

128 128 3
[[8, 8], [16, 16], [32, 32], [64, 64]]
(?, 128, 128, 3)
(?, 128, 128, 3)
Traceback (most recent call last):20000 ] |                                                                                                                                                                      | (ETA:  --:--:--) 
  File "/localhome/demo/autoencoder_6d_pose_estimation/venv/bin/ae_train", line 11, in <module>
    load_entry_point('auto-pose==0.9', 'console_scripts', 'ae_train')()
  File "/localhome/demo/autoencoder_6d_pose_estimation/venv/local/lib/python2.7/site-packages/auto_pose/ae/ae_train.py", line 90, in main
    dataset.get_training_images(dataset_path, args)
  File "/localhome/demo/autoencoder_6d_pose_estimation/venv/local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 93, in get_training_images
    self.render_training_images()
  File "/localhome/demo/autoencoder_6d_pose_estimation/venv/local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 246, in render_training_images
    bgr_x, depth_x = self.renderer.render( 
  File "/localhome/demo/autoencoder_6d_pose_estimation/venv/local/lib/python2.7/site-packages/auto_pose/ae/utils.py", line 15, in decorator
    setattr(self, attribute, function(self))
  File "/localhome/demo/autoencoder_6d_pose_estimation/venv/local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 75, in renderer
    float(self._kw['vertex_scale'])
  File "/localhome/demo/autoencoder_6d_pose_estimation/venv/local/lib/python2.7/site-packages/auto_pose/meshrenderer/meshrenderer_phong.py", line 48, in __init__
    for vertex, normal, color, faces in attributes:
ValueError: need more than 3 values to unpack

It' look like the attributes are not correctly loaded, as I check the attributes in debug mode the size of attributes is 3 not 4. The 3d model I use is T-LESS models_cad/obj_01.ply. I tried other .ply meshes and have also problems. 
the background image:  VOCdevkit/VOC2012/JPEGImages/'.jpg

**System Info**
My environment:
I'm using pycharm virtualenvironment
 * GPU: GeForce GTX 1050 
 * Python 2.7
 * PyOpenGL 3.1.3b2
 * PyOpenGl-accelerate 3.1.3b1 

thanx..

**Comment by MartinSmeyer** [comment]
yes, you have to change the model type in the config file from "reconst" to "cad" if you use CAD models for training:

MODEL: reconst
to 
MODEL: cad

**Comment by eyildiz-ugoe** [comment]
I don't have CAD model but get the same error. This is the output when it is set to `reconst`:

```
Instructions for updating:
Use the retry module or similar alternatives.
128 128 3
[[8, 8], [16, 16], [32, 32], [64, 64]]
(?, 128, 128, 3)
(?, 128, 128, 3)
100% |##############################################################################################################################|
Traceback (most recent call last):
  File "/home/username/.local/bin/ae_train", line 10, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python2.7/site-packages/auto_pose/ae/ae_train.py", line 90, in main
    dataset.get_training_images(dataset_path, args)
  File "/home/username/.local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 93, in get_training_images
    self.render_training_images()
  File "/home/username/.local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 246, in render_training_images
    bgr_x, depth_x = self.renderer.render( 
  File "/home/username/.local/lib/python2.7/site-packages/auto_pose/ae/utils.py", line 15, in decorator
    setattr(self, attribute, function(self))
  File "/home/username/.local/lib/python2.7/site-packages/auto_pose/ae/dataset.py", line 75, in renderer
    float(self._kw['vertex_scale'])
  File "/home/username/.local/lib/python2.7/site-packages/auto_pose/meshrenderer/meshrenderer_phong.py", line 45, in __init__
    for vertex, normal, color, faces in attributes:
ValueError: need more than 3 values to unpack
```

and I tried setting it to `cad` as well, which resulted with:

```
Instructions for updating:
Use the retry module or similar alternatives.
128 128 3
[[8, 8], [16, 16], [32, 32], [64, 64]]
(?, 128, 128, 3)
(?, 128, 128, 3)
Segmentation fault (core dumped)   
```

**Comment by eyildiz-ugoe** [comment]
@MartinSmeyer  This error occurs whichever value I enter, cad or reconst. Please see https://github.com/DLR-RM/AugmentedAutoencoder/issues/9
