### ISSUE TITLE
TypeError running ae_train

### ISSUE THREAD

**Issue by Zaxorn** [DLR-RM/AugmentedAutoencoder#79]
Hello, thanks for sharing your amazing work.

I was trying to run the ae_train script with a custom.ply object model and a black background for the object orientation.
 When I run the script I get the following error after loading training and background images

`
Traceback (most recent call last):
  File "ae_train.py", line 157, in <module>
    main()
  File "ae_train.py", line 114, in main
    summary_writer = tf.summary.FileWriter(ckpt_dir, sess.graph)
  File "/home/manuel/Desktop/AugmentedAutoencoder/env/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py", line 367, in __init__
    filename_suffix)
  File "/home/manuel/Desktop/AugmentedAutoencoder/env/lib/python3.6/site-packages/tensorflow/python/summary/writer/event_file_writer.py", line 68, in __init__
    self._event_queue = six.moves.queue.Queue(max_queue)
TypeError: __init__() missing 3 required positional arguments: 'num_threads', 'queue_size', and 'batch_size'
`
I'm using tensorflow 1.14 (installed from requirements.txt).

Any suggestions? Thanks in advance

**Comment by saqib1707** [comment]
Hello, I am also facing this same issue. Can someone provide any solution ? TIA

**Comment by saqib1707** [comment]
If anyone else is facing this issue:
Try building the AAE package first using the setup.py file as mentioned in the README.md. 
```
pip install --user .
```
Earlier, I was directly running the ae_train.py using python command.
