### ISSUE TITLE
RuntimeError: Bindless Textures not supported

### ISSUE THREAD

**Issue by Yuaika** [DLR-RM/AugmentedAutoencoder#82]
When I run commond "ae_train exp_group/my_autoencoder -d ",it outputs "RuntimeError: Bindless Textures not supported".

Details:
using egl   0% |                                     | 0 / 20000 ETA:  --:--:-- 
Traceback (most recent call last):
  File "/home/yuaika/.local/bin/ae_train", line 8, in <module>
    sys.exit(main())
  File "/home/yuaika/.local/lib/python3.7/site-packages/auto_pose/ae/ae_train.py", line 87, in main
    dataset.get_training_images(dataset_path, args)
  File "/home/yuaika/.local/lib/python3.7/site-packages/auto_pose/ae/dataset.py", line 95, in get_training_images
    self.render_training_images()
  File "/home/yuaika/.local/lib/python3.7/site-packages/auto_pose/ae/dataset.py", line 247, in render_training_images
    bgr_x, depth_x = self.renderer.render(
  File "/home/yuaika/.local/lib/python3.7/site-packages/auto_pose/ae/utils.py", line 15, in decorator
    setattr(self, attribute, function(self))
  File "/home/yuaika/.local/lib/python3.7/site-packages/auto_pose/ae/dataset.py", line 78, in renderer
    float(self._kw['vertex_scale'])
  File "/home/yuaika/.local/lib/python3.7/site-packages/auto_pose/meshrenderer/meshrenderer_phong.py", line 18, in __init__
    self._context = gu.OffscreenContext()
  File "/home/yuaika/.local/lib/python3.7/site-packages/auto_pose/meshrenderer/gl_utils/egl_offscreen_context.py", line 83, in __init__
    raise RuntimeError("Bindless Textures not supported")
RuntimeError: Bindless Textures not supported

**Comment by MartinSmeyer** [comment]
If you want to display the training images with -d you need a connected monitor. If you just want to train, you can remove the -d and it should work

**Comment by saqib1707** [comment]
> If you want to display the training images with -d you need a connected monitor. If you just want to train, you can remove the -d and it should work

Even after removing the -d option, the error "Bindless Textures not supported" persists. @MartinSmeyer
