### ISSUE TITLE
[question] Generating pose for own images

### ISSUE THREAD

**Issue by B-Acharya** [DLR-RM/AugmentedAutoencoder#96]
Hello,
I have been trying to use your code[multipath] to generate poses for objects. Till now i have managed to train a model (but due to some gpu issues i couldnt not create codebooks for them ) and wanted to use your codebooks that you have provided to test it out on ycbv dataset . But everytime i run the command 
`python auto_pose/m3_interface/compute_bop_results_m3.py auto_pose/ae/cfg_m3vision/m3_config_lmo_mp.cfg --eval_name test --dataset_name=ycbv --datasets_path=/home/clf/bop_toolkit/ --result_folder /home/clf/DLR-RM/results/ -vis`

i get the error 

> tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/clf/DLR-RM/experiments/multi_object/bop_except_itodd/checkpoints/chkpt-joint-800000

i dont completely understand this error , could you point me the what direction i have to be looking to solve this error .

python version - 2.7

**Comment by B-Acharya** [comment]
update: 
changing the code in mp_pose_estimator.py from 
`checkpoint_file = utils.get_checkpoint_basefilename(log_dir, False, latest=self.train_args.getint('Training', 'NUM_ITER'), joint=True)`
To
 'checkpoint_file = utils.get_checkpoint_basefilename(log_dir, False, latest=self.train_args.getint('Training', 'NUM_ITER'), joint=False)'
helped me solve the above issue but i seem to be facing a new error 

> 
2021-06-29 19:18:41.053752: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-06-29 19:18:41.150589: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-29 19:18:41.151045: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5569de4f3260 executing computations on platform CUDA. Devices:
2021-06-29 19:18:41.151064: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1050 Ti, Compute Capability 6.1
2021-06-29 19:18:41.153411: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2799925000 Hz
2021-06-29 19:18:41.153889: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5569de4f3490 executing computations on platform Host. Devices:
2021-06-29 19:18:41.153911: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2021-06-29 19:18:41.154139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 1.79GiB
2021-06-29 19:18:41.154164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2021-06-29 19:18:41.155041: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-29 19:18:41.155072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2021-06-29 19:18:41.155081: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2021-06-29 19:18:41.155212: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2020 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
WARNING:tensorflow:From /home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2021-06-29 19:18:41.225274: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key bop_except_itodd/embed_obj_bbs_var not found in checkpoint
Traceback (most recent call last):
  File "auto_pose/m3_interface/compute_bop_results_m3.py", line 93, in <module>
    mp_pose_estimator = MPPoseEstimator(m3_config_path)
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/auto_pose/m3_interface/mp_pose_estimator.py", line 78, in __init__
    saver.restore(self.sess, checkpoint_file)
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1292, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key bop_except_itodd/embed_obj_bbs_var not found in checkpoint
         [[node save/RestoreV2 (defined at /home/clf/dlr-rm/local/lib/python2.7/site-packages/auto_pose/m3_interface/mp_pose_estimator.py:77) ]]
         [[node save/RestoreV2 (defined at /home/clf/dlr-rm/local/lib/python2.7/site-packages/auto_pose/m3_interface/mp_pose_estimator.py:77) ]]

Caused by op u'save/RestoreV2', defined at:
  File "auto_pose/m3_interface/compute_bop_results_m3.py", line 93, in <module>
    mp_pose_estimator = MPPoseEstimator(m3_config_path)
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/auto_pose/m3_interface/mp_pose_estimator.py", line 77, in __init__
    saver = tf.train.Saver()
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key bop_except_itodd/embed_obj_bbs_var not found in checkpoint
         [[node save/RestoreV2 (defined at /home/clf/dlr-rm/local/lib/python2.7/site-packages/auto_pose/m3_interface/mp_pose_estimator.py:77) ]]
         [[node save/RestoreV2 (defined at /home/clf/dlr-rm/local/lib/python2.7/site-packages/auto_pose/m3_interface/mp_pose_estimator.py:77) ]]

**Comment by MartinSmeyer** [comment]
Hi,

If you are using the `bop_except_itodd` model, you also need to pass the corresponding config into `auto_pose/m3_interface/compute_bop_results_m3.py`. It is inside the folder downloaded folder.

Currently you have `auto_pose/ae/cfg_m3vision/m3_config_lmo_mp.cfg` there. You probably also need to undo the change you did.

**Comment by B-Acharya** [comment]
Hello Thank you for your response, but it was a mistake from my side when i created the issue . 
I have been using the right ycbv config file i just made a mistake when posting the issue 
`python auto_pose/m3_interface/compute_bop_results_m3.py auto_pose/ae/cfg_m3vision/m3_config_ycbv_mp.cfg --eval_name test --dataset_name=ycbv --datasets_path=/home/clf/bop_toolkit/ --result_folder /home/clf/DLR-RM/results/ -vis`
To confirm this is the command i ma currently running and i still face issues

**Comment by B-Acharya** [comment]
Hello Thank you for your response, but it was a mistake from my side when i created the issue .
I have been using the right ycbv config file i just made a mistake when posting the issue
python auto_pose/m3_interface/compute_bop_results_m3.py auto_pose/ae/cfg_m3vision/m3_config_ycbv_mp.cfg --eval_name test --dataset_name=ycbv --datasets_path=/home/clf/bop_toolkit/ --result_folder /home/clf/DLR-RM/results/ -vis
To confirm this is the command i am currently running and i still face issues.

Also based on your previous comment to pass the bop_except_itodd.cfg file to auto_pose/m3_interface/compute_bop_results_m3.py i tried this and got the following error 
`File "/home/clf/dlr-rm/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1228, in _unify_values
    raise NoSectionError(section)
backports.configparser.NoSectionError: No section: 'methods'
`

**Comment by MartinSmeyer** [comment]
ah okay, yes sry.

**Comment by MartinSmeyer** [comment]
The original issue said that the codebook creation was unsuccessful without further details. However, it is a necessary step in order to use the model. Codebooks can not be reused from elsewhere, they have to be generated for the specific Multipath Encoder. I think that was the misunderstanding.
